@domain = http://localhost:3000

###
GET {{domain}}/events

###

POST {{domain}}/register
Content-Type: application/json

{
    "name": "ellen vitoria",
    "email": "ellene@gmail.com",
    "password": "123456",
    "phone": "839999999999",
    "birth": "2007-08-21"
}

###
POST {{domain}}/inscricao/new/1/1
Content-Type: application/json

{
    "qrCode": "https://via.placeholder.com/100x100.png?text=QR+Code",
    "cpf": "12059930456",
    "price": "R$ 565,00",
    "transaction": "CHAR_C68ER45-89RW-5T6W-CV67-963243TYYU7I9",
    "instructions": "Mostre o voucher no seu smartphone ou impresso, acompanhado de um documento oficial válido com foto. Certifique-se de que o código de barras esteja legível."
} 

### login
# @name login
POST {{domain}}/login
Content-Type: application/json

{
    "loginEmail": "coldplay@example.com",
    "loginPassword": "password"
}

### VERIFY-AUTH
GET {{domain}}/verify-auth
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMTkzMTE3Nn0.KCh1R7uS5nN2WSlkGU32riiiKAj13aEjEBMBsbAv1WU